148 separate emg outputs in hdf5 by dig in
abuzarmahmood/blech_clust pull request #153
Opened 2024-02-21 01:08 UTC by abuzarmahmood

Update EMG pipeline to allow:

- Simpler handling of trial metadata (taste, laser) using dataframes
- Process emg data without chunking into tastes (simplifies code, and better handles uneven trials)

Includes output of a `trial_info_frame` which is human-readable, and contains all metadata associated with a trial.

2024-02-21 01:10 UTC, abuzarmahmood commented
1. Merge `emg_plot_filt_env` into `emg_filter`
2.

2024-02-23 16:25 UTC, abuzarmahmood commented
**All tests passed**

2024-02-23 18:05 UTC, hfgem requested changes
See comments - changes needed and new issues needed.

2024-02-23 18:11 UTC, abuzarmahmood commented on emg/emg_freq_setup.py
> +print('Deleting emg_BSA_results')
Created an issue for future work

2024-02-23 18:12 UTC, abuzarmahmood commented on emg/gape_QDA_classifier/get_gapes_Li.py
> +        if dur > 20.0 and dur <= 200.0:
Agreed, but "technically" this step is a part of the classifier...I didn't bother changing it.

2024-02-23 18:12 UTC, abuzarmahmood commented on emg/gape_QDA_classifier/get_gapes_Li.py
> +        mpd=85,
Same as above comment.

2024-02-23 18:14 UTC, hfgem approved these changes
LGTM

2024-02-23 18:14 UTC, merged